### ISSUE TITLE
Jeff holiday to-do list

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#871]
* [x] Get Mobilito MVP done asap.
* [x] Clean up the publication model, #869.
* [x] Comb through TB and make sure all buttons always make sense.
* [x] Record session cookie in stripe app, #805.
* [x] Record a boolean, whether authenticated or not, it utm records.
* [x] Add contact info to TBPress, should display in mail but not on web (privacy).
* [x] Make a sendable summary, #870.
* [x] Provide sendable sending feedback #872.
* [x] Clean up press mention, #867.
* [ ] Clean up issues.

**Comment by Shriukan33** [comment]
About Clean up press mention, #867 , @mcmikashi opened a PR but I didn't check the changes against the issue's content yet
